version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src/:/app
    container_name: app
    restart: always
    networks:
      - container-link
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ./src/:/app
    container_name: web
    ports:
      - 8081:80
    restart: always
    networks:
      - container-link
    depends_on:
      - app

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    volumes:
      - mysql-volume:/var/lib/mysql
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    networks:
      - container-link

volumes:
  mysql-volume:

networks:
  default:
    external: true
    name: bridge
  container-link:
    name: sample_nw
